# FOR DEV
spring:
  datasource:
    url: jdbc:mysql://dev-db:3306/flight_db
    username: dev_user
    password: dev_password
    driver-class-name: com.mysql.cj.jdbc.Driver

  rabbitmq:
    host: dev-rabbitmq
    port: 5672
    username: guest
    password: guest

custom:
  cache-enabled: true 