spring:
  application:
    name: airline-flight-service
  profiles:
    active: 
  datasource:
    url: jdbc:mysql://localhost:3306/flight_db?useSSL=false
    username: dev_user
    password: dev_pass
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    registry-fetch-interval-seconds: 5  # 快速获取注册表更新

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG  # 开发环境显示 SQL 日志