spring:
  application:
    name: airline-booking-service
  datasource:
    url: jdbc:mysql://localhost:3306/booking_db?useSSL=false
    username: booking_user
    password: booking_pass
  redis:
    host: localhost
    port: 6379
    password: redis_pass

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

# 自定义配置示例
booking:
  max-retries: 3
  timeout-ms: 5000